### ISSUE TITLE
Failed to construct 'WebSocket'

### ISSUE THREAD

**Issue by ndan** [lustre-labs/dev-tools#24]
I followed the guide at https://hexdocs.pm/lustre/guide/01-quickstart.html, but I can't get it to work.

MacOS Sonoma 14.4 (Apple M2)
gleam 1.1.0-rc3 (because lustre_dev_tools requires Gleam 1.1.0)

### Steps to reproduce
1. gleam new app && cd app && gleam add lustre
2. add `target = "javascript"` to gleam.toml
3. add "Hello, world!"
```gleam
import lustre
import lustre/element

pub fn main() {
  lustre.element(element.text("Hello, world!"))
}
```
4. gleam add --dev lustre_dev_tools
5. gleam run -m lustre/dev start
<img width="1229" alt="image" src="https://github.com/lustre-labs/dev-tools/assets/760394/5021b952-4da5-4c9e-af41-ae806ce92d33">

**Comment by hayleigh-dot-dev** [comment]
Hey thanks for the issue! I just did a quick check and this seems like a rather sneaky difference between safari and chrome! 

I've fixed it now and I'll publish a patch release shortly ❤️

**Comment by hayleigh-dot-dev** [comment]
Published!
