### ISSUE TITLE
Add `--no-tailwind` or similar to stop Tailwind detection

### ISSUE THREAD

**Issue by okkdev** [lustre-labs/dev-tools#25]
Hi, I use [glailglind](https://github.com/okkdev/glailglind) to handle tailwind. 
I'd like to be able to tell the dev tools to not worry about tailwind. :)

**Comment by hayleigh-dot-dev** [comment]
Sounds like a reasonable suggestion, I'll take a look!

**Comment by hayleigh-dot-dev** [comment]
You can now disabled the tailwind detection by passing `--tailwind-detect=false`
