### ISSUE TITLE
Add `--inpufile` to define a starting point for tailwind

### ISSUE THREAD

**Issue by Neophen** [lustre-labs/dev-tools#26]
Most users are used to having `app.css` or something where we do tailwind setup, this also allows for an easy way to add some extra css classes/components with tailwind layers. the example bellow is a bit more involved. but it portrays the point

```
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@import './components/buttons.css';
@import './components/fields.css';
@import './components/loader.css';
@import './components/modal.css';
@import './components/stack.css';

@layer base {
  html:has(dialog[open]) {
    overflow: hidden;
  }
}
```

Not sure if this is a use case for the dev tools or not.

Thank you for your awesome work!

**Comment by hayleigh-dot-dev** [comment]
You can now supply the `--tailwind-entry` flag.
