### ISSUE TITLE
Tailwind: update readme to note that you must include the css file similar to lustre_ui

### ISSUE THREAD

**Issue by xpressivecode** [lustre-labs/dev-tools#30]
It might just be me, but when I first read the readme: "Automatic detection and support for TailwindCSS." I made the assumption that after adding tailwind it would just work. But I had to update the index.html file to include the stylesheet, which makes sense. But it wasn't immediately made clear in the installation directions. When comparing that with the lustre_ui package, it has a small section letting you know to include the css files.

A small quality of life improvement could be scanning the index.html file to see if the stylesheet is missing from head and including it after the write_tailwind_config call. Or alternatively mention it in the output of the cli to include the css file after running the add tailwind command.

**Comment by hayleigh-dot-dev** [comment]
>  Or alternatively mention it in the output of the cli to include the css file after running the add tailwind command.

Mentioning it in the CLI output is a great idea. Previously we did used to inject the css directly into the HTML but we switched to generating the HTML once (if it's missing) and letting it be user-editable from there. 

Great suggestion, I'll get round to it soon!
