### ISSUE TITLE
Websocket connection issues

### ISSUE THREAD

**Issue by mooreryan** [lustre-labs/dev-tools#39]
I'm not sure if this is something that the dev_tools even has any control over, but if you run a project with `gleam run -m lustre/dev start`, then navigate google chrome to the http://localhost:1234, then force close the devtools with `Ctrl-c Ctrl-c`, after a couple of moments you get this:

![lustre_dev_tools_bug_2](https://github.com/lustre-labs/dev-tools/assets/3172014/0bae5827-dec0-4178-94b7-b37b06d5abae)

and eventually this:

![lustre_dev_tools_bug](https://github.com/lustre-labs/dev-tools/assets/3172014/b05b5f2a-4e7c-4cfd-8e8a-5f42790d37cd)

in which eventually 100% of the cpu is being used.

Is this just a browser issue, or something that dev_tools could address?

**Comment by hayleigh-dot-dev** [comment]
> in which eventually 100% of the cpu is being used.

LOL that is not good. The client is supposed to periodically check to see if the connection is back (this is nice because if you restart the dev server you can pick up where you left off) but I guess there is a bug with the logic and maybe we have a memory leak or something.

I'll investigate :)

**Comment by hayleigh-dot-dev** [comment]
OK this should be solved now – if its still not working correctly after this release I will just remove the reconnect logic for the timebeing, please re-open the issue if you run into it again.
