### ISSUE TITLE
Dev server proxy not working properly

### ISSUE THREAD

**Issue by Robert4S** [lustre-labs/dev-tools#41]
I am trying to use the dev server proxy to proxy a lustre frontend to my rust backend, but the proxy urls don't seem to work properly. I run the dev server with the following 
`gleam run -m lustre/dev start --proxy-from=api/ --proxy-to=http://127.0.0.1:8080/api`
and then doing a `gleam_http.post` to "api/login", which afaik should route to http://127.0.0.1:8080/api/login, which is a route that works through postman, but with the dev server I just get `BadUrl("api/login")`

**Comment by Robert4S** [comment]
it works with the full, non proxied url

**Comment by hayleigh-dot-dev** [comment]
I'll leave this here for posterity, in case others come across this issue. This is currently an [issue with the lustre_http package](https://codeberg.org/kero/lustre_http/issues/5) where requests can only be made to full urls.

Hopefully this will get resolved soon ^.^
