### ISSUE TITLE
Proxy doesn't correctly pass HTTP method

### ISSUE THREAD

**Issue by techninja1008** [lustre-labs/dev-tools#45]
When using the proxy feature of the dev server, all requests are made to the backend side as GET requests, rather than the correct method of the incoming request.

**Comment by hayleigh-dot-dev** [comment]
Oh how odd, I'll investigate! Thanks.

**Comment by hayleigh-dot-dev** [comment]
OK I think this is fixed in the latest release. Please can you check and open a new issue if there are new and exciting problems as a consequence ^.^
