### ISSUE TITLE
Update `gleam_json` dependency version

### ISSUE THREAD

**Issue by yoonthegoon** [lustre-labs/dev-tools#52]
I run the following and get:

```sh
$ gleam add lustre_dev_tools --dev
  Resolving versions
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to find compatible versions for the version constraints in your
gleam.toml. The conflicting packages are:

- gleam_json
- gleam_package_interface
- gleam_stdlib
- lustre_dev_tools
```

I've read #27 and downgraded `gleam_stdlib` to `0.36.0`.  
However, that isn't the root of this issue.

I'm currently using `gleam_stdlib@0.39.0` and am able to add `lustre_dev_tools`.  
I had to use `gleam_json@1.0.1` in order to do so.

Please update the `gleam_json` dependency version if possible.  
Thanks ❤️

**Comment by hayleigh-dot-dev** [comment]
i cannot update the gleam_json version until wisp updates theirs unfortunately. The previous release  had a wide enough constraint that meant you could use v1 or v2 but it was still causing problems because of wisp.

**Comment by yoonthegoon** [comment]
All good, glad to know where the constraint is from at least. Thanks
