### ISSUE TITLE
dynamic.unsafe_coerce is not available

### ISSUE THREAD

**Issue by ahankinson** [lustre-labs/dev-tools#69]
Trying to run the "Getting Started" tutorial, I run: 

`$ gleam run -m lustre/dev start`

And I get this message:

```
error: Unknown module field
   ┌─ /Users/ahankins/Documents/code/rism/learn/lustretest/build/packages/glisten/src/glisten/socket/options.gleam:58:40
   │
58 │   |> list.map(pair.map_first(_, dynamic.unsafe_coerce))
   │                                        ^^^^^^^^^^^^^^

The module `gleam/dynamic` does not have a `unsafe_coerce` value.

error: Unknown module field
   ┌─ /Users/ahankins/Documents/code/rism/learn/lustretest/build/packages/glisten/src/glisten/socket/options.gleam:80:22
   │
80 │   |> list.map(dynamic.unsafe_coerce)
   │                      ^^^^^^^^^^^^^^

The module `gleam/dynamic` does not have a `unsafe_coerce` value.
```

`glisten` [has already removed this call](https://github.com/rawhat/glisten/blob/master/CHANGELOG.md), but somewhere in the dependencies for the dev tools it's pinned to an earlier version.

**Comment by hayleigh-dot-dev** [comment]
It's not a problem with dev tools it's a problem with [wisp](https://github.com/gleam-wisp/wisp/pull/93). When they release this PR we can update our dependencies.

Until then you can workaround the issue by fixing your stdlib to 0.39.0

**Comment by hayleigh-dot-dev** [comment]
I'll leave this open because I suspect more folks will come across this until wisp is updated!

**Comment by ahankinson** [comment]
> Until then you can workaround the issue by fixing your stdlib to 0.39.0

Thanks! Do you have any idea how to do that? I set `gleam_stdlib = "<= 0.39.0"` in my gleam.toml, but I'm still getting the same error.

**Comment by hayleigh-dot-dev** [comment]
Yeah you just need to do `gleam_stdlib = "0.39.0"` ^.^ Because the stdlib is still v0 for the time being these kind of things happen from time to time. It'll just be a few days before everyone catches up so thanks for being patient!

**Comment by hayleigh-dot-dev** [comment]
Everything should be updated and good to go!

**Comment by ahankinson** [comment]
It works! Thank you so much.
