### ISSUE TITLE
Ignore Vim swap files when copying to build/dev/javascript

### ISSUE THREAD

**Issue by EgZvor** [lustre-labs/dev-tools#70]
Hello, I use Vim and I encountered an error with `gleam run -m lustre/dev start`

```
I ran into an error while trying to read the following file:

    ./src/.lustre_example.gleam.swp

Here's the error message I got:

    NotUtf8
```

`.swp` is a Vim swap file which is binary. It can have other extensions too like `.swo`.

Perhaps skipping hidden files is a good idea. I don't really understand why it tries to bundle *all* the files from the source directory.

**Comment by hayleigh-dot-dev** [comment]
🤔 Could you show the full output from when you run the command please!

**Comment by hayleigh-dot-dev** [comment]
Ah I see it, I can fix this.
