### ISSUE TITLE
Infinite build & reload loop when saving FFI file

### ISSUE THREAD

**Issue by mdarse** [lustre-labs/dev-tools#71]
When using the live reload feature (`gleam run -m lustre/dev start`), each time I save an FFI (.mjs) file, the process fall in an infinite loop that triggers infinite reloads in the browser.

I run macOS 14.6.1, and could reproduce the issue with multiple editors including Zed & vi.

After quite a bit of digging around the `fs` module I found that after an initial (and correct) change detected on the saved FFI file (with events `[Inodemetamod, Modified]`), I get another change on this same file with the same events but a change on every other FFI files with the `[]` events. Then this loops again.

I’ve found a workaround by commenting out these two lines.
https://github.com/lustre-labs/dev-tools/blob/10452a048fba334659216a38d48ddd4cbe2e6758/src/lustre_dev_tools/cli/build.gleam#L76-L77

So the issue seems related to the gleam compiler exporting the package information (or an interaction between this and the regular build process).

Sometime the build loop stops after some time, most of the time not. So we may have a race somewhere.

**Comment by hayleigh-dot-dev** [comment]
Dev tools no longer checks module interface when building apps as this functionality is broken in the gleam compiler, which means this issue is likely also resolved. Closing for now but if it comes up again please do open a new issue!
