### ISSUE TITLE
Start command description outdated on automatic reload

### ISSUE THREAD

**Issue by voneiden** [lustre-labs/dev-tools#72]
(`gleam-1.5.0`, `lustre_dev_tools-1.5.7`)

Package docs mention automatic reload

https://github.com/lustre-labs/dev-tools/blob/90fcbeff8451aebf264a094ad4a55fd0e16823af/src/lustre/dev.gleam#L154-L155

And I see there was #22 however the CLI help states that live reload is not available:

https://github.com/lustre-labs/dev-tools/blob/90fcbeff8451aebf264a094ad4a55fd0e16823af/src/lustre_dev_tools/cli/start.gleam#L28-L29

Presumably the description is outdated?

**Comment by hayleigh-dot-dev** [comment]
Oh yeah good spot, thank you, I'll fix that now!
