### ISSUE TITLE
Development server does not reload with versions 1.5.6 and 1.5.7

### ISSUE THREAD

**Issue by voneiden** [lustre-labs/dev-tools#73]
(Tested with `gleam-1.5.0` and `gleam-1.4.0`, linux, inotify installed)

With `lustre_dev_tools-1.5.7` it looks to me like the reload triggers but hits an error when attempting to run the [lustre example](https://hexdocs.pm/lustre/index.html#example)
 

` gleam run -m lustre/dev start`

I get an error twice at the moment the reload should happen

```
  Compiling lustretest
   Compiled in 0.23s
    Running lustre/dev.main
✅ Project compiled successfully
✅ Esbuild already installed!
✅ Bundle produced at `./priv/static/lustretest.mjs`
Listening on http://localhost:1234
                 
I couldn't find the following module:
   
    lustretest

Make sure the module path is correct and also the module is not included in the
`internal_modules` list in your `gleam.toml`.

The Gleam compiler currently has a bug with it's package-interface export that
will affect lustre_dev_tools. You can find more information about that bug here:
                                                                      
    https://github.com/gleam-lang/gleam/issues/2898

If you know the above module exists, try running `gleam clean` and then run the
dev tools again. If you think this is a bug, please open an issue on GitHub with
some details about what you were trying to do when you ran into this issue:
   
    https://github.com/lustre-labs/dev-tools/issues/new
```

(So "I couldn't find the following module:" is generated two times in a row. Just a minor detail)

With `lustre_dev_tools-1.5.6` I get a crash which to my understanding was a known issue and a fix was maybe attempted in https://github.com/lustre-labs/dev-tools/commit/081b5e7a28dccb9399237d181d8985b09aa4a0a5 ? The intent is not quite clear from the commit message. 

```
runtime error: Erlang exit

A function was called but it did not exist.

erlang:exit(Undef)

stacktrace:
  glearray.get unknown source
  spinner.frame lustretest/build/packages/spinner/src/spinner.gleam:109
  spinner.print lustretest/build/packages/spinner/src/spinner.gleam:100
  spinner.-start/1-fun-0- lustretest/build/packages/spinner/src/spinner.gleam:68
  repeatedly_ffi.handle_info lustretest/build/dev/erlang/repeatedly/_gleam_artefacts/repeatedly_ffi.erl:46
  gen_server.try_handle_info gen_server.erl:1095
  gen_server.handle_msg gen_server.erl:1183
  proc_lib.init_p_do_apply proc_lib.erl:241
```

With `lustre_dev_tools-1.5.5` auto reload appears to work just fine. Both `gleam-1.5.0` and `gleam-1.4.0`.

**Comment by hayleigh-dot-dev** [comment]
The error you are seeing in 1.5.7 is because we no longer attempt to work around a Gleam compiler bug, the message links to the GitHub issue that describes the problem.

If 1.5.5 is working for you feel free to keep using it there are no feature differences between that and 1.5.7 (and you're right that 1.5.6 was a dud); hopefully that Gleam issue is fixed soon.

**Comment by voneiden** [comment]
Ok, that clears things up, thanks! I'll stick to 1.5.5 and keep an eye on https://github.com/gleam-lang/gleam/issues/2898
