### ISSUE TITLE
Error starting up the dev server

### ISSUE THREAD

**Issue by AlexanderVanDamme** [lustre-labs/dev-tools#77]
╭─alisk@khuinux in repo: football_matchmaking on  master [!?] via ⭐ v1.5.1 via  v23.1.0 took 0s
 ╰─λ gleam run -m lustre/dev start
   Compiled in 0.17s
    Running lustre/dev.main
✅ Project compiled successfully
✅ Esbuild already installed!
✅ Bundle produced at `./priv/static/football_matchmaking.mjs`
✅ Tailwind already installed!

Next Steps:

1. Be sure to update your root `index.html` file to include 
   `<link rel='stylesheet' type='text/css' href='./priv/static/your_app.css' />`
✅ Bundle produced at `./priv/static/football_matchmaking.css`

I ran into an error while trying to start the development server. Here's the
error message I got:

    AcceptorFailed(Abnormal("Child failed to start during initialisation: Abnormal(\"Failed to start socket listener: Eaddrinuse\")"))

Please open an issue at https://github.com/lustre-labs/dev-tools/issues/new with
some details about what you were trying to do when you ran into this issue.

I did a gleam update after that but it still fails:

alisk@khuinux in repo: football_matchmaking on  master [!?] via ⭐ v1.5.1 via  v23.1.0 took 1s
 ╰─λ gleam update
  Resolving versions
Downloading packages
 Downloaded 9 packages in 0.81s

 ╭─alisk@khuinux in repo: football_matchmaking on  master [!?] via ⭐ v1.5.1 via  v23.1.0 took 16s
 ╰─λ gleam run -m lustre/dev start
  Compiling gleam_stdlib
  Compiling ranger
  Compiling birl
  Compiling gleam_json
  Compiling stoiridh_version
  Compiling decipher
  Compiling decode
  Compiling envoy
  Compiling filepath
  Compiling simplifile
  Compiling directories
  Compiling exception
  Compiling gleam_community_colour
  Compiling gleam_community_ansi
  Compiling gleam_crypto
  Compiling gleam_erlang
  Compiling gleam_http
  Compiling gleam_javascript
  Compiling gleam_fetch
  Compiling gleam_httpc
  Compiling gleam_otp
  Compiling gleam_package_interface
  Compiling glearray
  Compiling gleeunit
  Compiling snag
  Compiling glint
  Compiling glisten
warning: Incompatible gleam version range
   ┌─ /home/alisk/Brogramming/football_matchmaking/build/packages/glisten/src/glisten.gleam:92:1
   │
92 │ @internal
   │ ^^^^^^^^^ This requires a Gleam version >= 1.1.0

The `@internal` annotation was introduced in version v1.1.0. But the Gleam
version range specified in your `gleam.toml` would allow this code to run
on an earlier version like v1.0.0, resulting in compilation errors!
Hint: Remove the version constraint from your `gleam.toml` or update it to be:

    gleam = ">= 1.1.0"

warning: Deprecated value used
    ┌─ /home/alisk/Brogramming/football_matchmaking/build/packages/glisten/src/glisten.gleam:318:9
    │
318 │     list.concat([ssl_options, protocol_options]),
    │         ^^^^^^^ This value has been deprecated

It was deprecated with this message: Use `list.flatten` instead.

  Compiling gramps
  Compiling lustre
  Compiling mist
  Compiling repeatedly
  Compiling spinner
  Compiling tom
  Compiling wisp
  Compiling lustre_dev_tools
warning: Deprecated value used
    ┌─ /home/alisk/Brogramming/football_matchmaking/build/packages/lustre_dev_tools/src/lustre_dev_tools/cli.gleam:267:23
    │
267 │   let toml_path = list.concat([["lustre-dev"], namespace, [name]])
    │                       ^^^^^^^ This value has been deprecated

It was deprecated with this message: Use `list.flatten` instead.

  Compiling lustre_http
warning: Unused imported module
  ┌─ /home/alisk/Brogramming/football_matchmaking/build/packages/lustre_http/src/lustre_http.gleam:2:1
  │
2 │ import gleam/fetch
  │ ^^^^^^^^^^^^^^^^^^ This imported module is never used

Hint: You can safely remove it.

warning: Unused imported module
  ┌─ /home/alisk/Brogramming/football_matchmaking/build/packages/lustre_http/src/lustre_http.gleam:6:1
  │
6 │ import gleam/javascript/promise
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ This imported module is never used

Hint: You can safely remove it.

warning: Unused variable
    ┌─ /home/alisk/Brogramming/football_matchmaking/build/packages/lustre_http/src/lustre_http.gleam:134:3
    │
134 │   req: Request(String),
    │   ^^^^^^^^^^^^^^^^^^^^ This variable is never used

Hint: You can ignore it with an underscore: `_req`.

warning: Unused variable
    ┌─ /home/alisk/Brogramming/football_matchmaking/build/packages/lustre_http/src/lustre_http.gleam:135:3
    │
135 │   expect: Expect(msg),
    │   ^^^^^^^^^^^^^^^^^^^ This variable is never used

Hint: You can ignore it with an underscore: `_expect`.

warning: Unused variable
    ┌─ /home/alisk/Brogramming/football_matchmaking/build/packages/lustre_http/src/lustre_http.gleam:136:3
    │
136 │   dispatch: fn(msg) -> Nil,
    │   ^^^^^^^^^^^^^^^^^^^^^^^^ This variable is never used

Hint: You can ignore it with an underscore: `_dispatch`.

   Compiled in 14.02s
    Running lustre/dev.main
✅ Project compiled successfully
✅ Esbuild already installed!
✅ Bundle produced at `./priv/static/football_matchmaking.mjs`
✅ Tailwind already installed!

Next Steps:

1. Be sure to update your root `index.html` file to include 
   `<link rel='stylesheet' type='text/css' href='./priv/static/your_app.css' />`
✅ Bundle produced at `./priv/static/football_matchmaking.css`

I ran into an error while trying to start the development server. Here's the
error message I got:

    AcceptorFailed(Abnormal("Child failed to start during initialisation: Abnormal(\"Failed to start socket listener: Eaddrinuse\")"))

Please open an issue at https://github.com/lustre-labs/dev-tools/issues/new with
some details about what you were trying to do when you ran into this issue.

**Comment by AlexanderVanDamme** [comment]
yesterday i could just startup this projects without problems

**Comment by AlexanderVanDamme** [comment]
restarting my pc fixed the problem

**Comment by hayleigh-dot-work** [comment]
If you run into this issue again, the error is you have some other program already using port `1234`. So you can proceed if you either
- kill the program on this port
- pass the `--port` option to dev tools and choose something other than the default port.

@giacomocavalieri do you think we could intercept this error and show something friendlier?

**Comment by giacomocavalieri** [comment]
Yeah I think we could do something about it! I can try and catch the error providing a better message :)
